### ISSUE TITLE
Installation with composer fails

### ISSUE THREAD

**Issue by simonmeggle** [robinlehrmann/lightify-api#1]
```
cat /etc/issue
Ubuntu 16.04.1 LTS \n \l
uname -a
Linux 63015e9513fd 4.4.27-moby #1 SMP Wed Oct 26 14:21:29 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

```
su - pluto 
pluto@63015e9513fd:~$ composer --version
Composer version @package_branch_alias_version@ (1.0.0-beta2) 2016-03-27 16:00:34
pluto@63015e9513fd:~$ composer require role/lightify-api
  [InvalidArgumentException]
  Could not find package role/lightify-api at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability
```

What is missing here? 
Thanks, 
Simon

**Comment by simonmeggle** [comment]
Solved by myself... `composer require`must be executed in the lightify-api folder *which must be a git clone*. One of my (afiled) attempts was to download the master.zip from github and exeute the command within the unzipped folder - which does not contain a .git folder.

**Comment by robinlehrmann** [comment]
Hi @simonmeggle 
You should upgrade your composer version. Try it by executing `composer self-update`.

If you want to use my lightify-api create a new project in a new folder.
Start with a clean composer.json but some custom content:
composer.json:
`{
"name": "vendor/some-project",
"config": {
"minimum-stability": "dev",
"prefer-stable": true
}
}`
Then execute `composer require role/lightify-api`

If the process is done you can create a php file like `index.php` and put this content in it:
`<?php
require_once __DIR__.'/vendor/autoload.php';

$lightifyApi = new Role\Lightify\LightifyApi($guzzleClient, $url, $userName, $password, $serialNumber);

// switch off device 2 without fade
 $deviceManager->toggle(2, false);
`

Don't forget to create a new .gitignore that ignores vendor directory.

**Comment by simonmeggle** [comment]
Hi @robinlehrmann ,
thanks for your help. 

Now I installed composer via cmdline to get the very latest version:
```
$ composer -V
Composer version 1.3.1 2017-01-07 18:08:51

$ cat composer.json
{
    "name": "vendor/foo-project",
    "config": {
        "minimum-stability": "dev",
        "prefer-stable": true
    }
}

$ php composer.phar require role/lightify-api
  [InvalidArgumentException]
  Could not find package role/lightify-api at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...
```

**Comment by robinlehrmann** [comment]
Hi, you should use the given config in my post. 

Change your minimum stability and prefer stable
